name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark:
          - tip5
          - ntt
          - evaluation
          - extrapolation
          - coset_extrapolation
          - poly_mod_reduce
          - interpolation
          - poly_mul
          - poly_scalar_mul
          - poly_scale
          - merkle_tree
          - merkle_tree_authenticate
          - merkle_tree_auth_structure_size
          - various_muls
          - zerofier
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Build benchmarks
        run: cargo codspeed build --bench ${{ matrix.benchmark }}

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run
          mode: "instrumentation"
          token: ${{ secrets.CODSPEED_TOKEN }}
